#' High-Precision Multi-Trait Cause-and-Effect Path Coefficient Analysis Engine
#'
#' @description
#' The `compute_path_analysis` function executes a complete phenotypic path coefficient analysis
#' based on the classic standard methodology of Dewey and Lu (1959). It partitions simple correlation
#' coefficients between causal developmental traits and a single target effect variable (e.g., Grain Yield)
#' into direct influence coefficients and indirect pathways acting through interconnected traits.
#'
#' @details
#' In complex plant breeding systems, selecting for terminal composite traits like yield can be misleading
#' if based purely on raw correlation coefficients. Path coefficient analysis provides a reliable
#' matrix-based resolution to this problem. Let \eqn{R} denote the symmetric correlation matrix among
#' the causal predictor traits, and \eqn{r} denote the vector of correlation coefficients between each
#' causal trait and the response variable. The standardized direct path coefficients (\eqn{\beta}) are calculated via:
#' \deqn{\beta = R^{-1} r}
#' Indirect effects are subsequent cross-products between the mutual correlations and direct coefficients.
#' The unexplained residual effect variation (\eqn{R_X}), representing factors outside the operational model, is derived as:
#' \deqn{R_X = \sqrt{1 - \sum (\beta_i \times r_i)}}
#'
#' @param correlation_payload A structured \code{list} directly generated by the package's
#'   \code{compute_correlation} module containing valid \code{correlation_matrix}.
#' @param response_trait A single character string specifying the exact name of the destination/effect column.
#' @param predictor_traits A character vector identifying the causal architectural predictor traits. 
#'   If \code{NULL}, the system assumes all remaining traits are causal components. Defaults to \code{NULL}.
#' @param reporting_level An integer vector flag defining console trace settings: \code{0} for silent,
#'   \code{1} for path effect grid summaries, and \code{2} for thorough diagnostic reporting. Defaults to \code{2}.
#'
#' @return A structured \code{list} containing the path partition arrays:
#'   \item{direct_effects}{A structured numeric vector storing the standardized direct path coefficients.}
#'   \item{indirect_effects_matrix}{A complete asymmetric data frame capturing cross-trait indirect paths.}
#'   \item{total_correlation_vector}{The original total phenotypic correlation alignment.}
#'   \item{residual_effect}{A numeric scalar value tracking the unexplained model residual variation.}
#'
#' @author Faheem Khan (\email{2022ag94@uaf.edu.pk})
#'
#' @seealso \code{\link{compute_correlation}}, \code{\link{compute_summary_stats}}
#'
#' @export
#'
#' @examples
#' \dontrun{
#'   corr_out <- compute_correlation(data = gv_data, method = "pearson", reporting_level = 0)
#'   path_out <- compute_path_analysis(correlation_payload = corr_out, response_trait = "GYPM")
#' }
compute_path_analysis <- function(correlation_payload, response_trait, predictor_traits = NULL, reporting_level = 2) {
  
  timestamp_start <- Sys.time()
  
  if (reporting_level >= 1) {
    cat(rep("=", 85), "\n", sep = "")
    cat("AGRIDATATOOLS PACKAGED ENGINE - MULTI-TRAIT PATH COEFFICIENT ENGINE\n")
    cat(rep("-", 85), "\n", sep = "")
  }
  
  if (missing(correlation_payload) || missing(response_trait)) {
    stop("CRITICAL MATRIX FAULT: Missing core arguments.", call. = FALSE)
  }
  
  full_corr_df <- correlation_payload$correlation_matrix
  all_traits   <- colnames(full_corr_df)
  
  if (!response_trait %in% all_traits) {
    stop("REGISTRATION FAULT: Response trait not found in matrix.", call. = FALSE)
  }
  
  if (is.null(predictor_traits)) {
    predictor_traits <- setdiff(all_traits, response_trait)
  }
  
  num_predictors <- length(predictor_traits)
  matrix_R       <- data.matrix(full_corr_df[predictor_traits, predictor_traits])
  vector_r       <- as.numeric(full_corr_df[predictor_traits, response_trait])
  names(vector_r) <- predictor_traits
  
  matrix_R_inv   <- solve(matrix_R)
  direct_effects <- as.numeric(matrix_R_inv %*% vector_r)
  names(direct_effects) <- predictor_traits
  
  indirect_matrix <- matrix(0, nrow = num_predictors, ncol = num_predictors,
                            dimnames = list(predictor_traits, predictor_traits))
  
  for (i in 1:num_predictors) {
    for (j in 1:num_predictors) {
      indirect_matrix[i, j] <- if (i == j) direct_effects[i] else matrix_R[i, j] * direct_effects[j]
    }
  }
  
  r_squared_explained <- sum(direct_effects * vector_r)
  residual_val        <- if (r_squared_explained > 1 || r_squared_explained < 0) 0 else sqrt(1 - r_squared_explained)
  
  df_path_grid <- as.data.frame(indirect_matrix)
  df_path_grid$Total_Correlation <- vector_r
  colnames(df_path_grid)[1:num_predictors] <- paste0("Path_", predictor_traits)
  
  if (reporting_level >= 1) {
    cat(" PATH COEFFICIENT DECOMPOSITION MATRIX (Target: ", response_trait, ")\n", sep = "")
    print(round(df_path_grid, 5))
    cat(" R^2: ", round(r_squared_explained, 5), " | Residual: ", round(residual_val, 5), "\n\n", sep = "")
  }
  
  return(invisible(list(
    direct_effects           = direct_effects,
    indirect_effects_matrix  = df_path_grid,
    total_correlation_vector = vector_r,
    residual_effect          = residual_val
  )))
}